# Generated by Django 2.1 on 2018-09-01 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(blank=True, max_length=250)),
                ('school_location', models.CharField(blank=True, max_length=250)),
                ('principal', models.CharField(blank=True, max_length=100)),
                ('school_email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, max_length=100)),
                ('student_age', models.PositiveIntegerField(blank=True)),
                ('student_gender', models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female')], max_length=6)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseApp.School')),
            ],
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='email',
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='age',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
