# Generated by Django 2.1 on 2018-09-02 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0002_auto_20180902_0849'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ModelDatabaseField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(choices=[('models.CharField(max_length=200,blank=True)', 'Character Field'), ('models.TextField(max_length=1000,blank=True)', 'Text Area Field'), ('model.BooleanField()', 'Boolean Field'), ('models.DateTimeField()', 'Date Time Field')], max_length=100)),
                ('model_database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseApp.ModelDatabase')),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='student_gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=6),
        ),
    ]
