# Generated by Django 2.1 on 2018-09-02 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0003_auto_20180902_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_code_name', models.CharField(max_length=20)),
                ('model_code', models.TextField()),
                ('model_database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseApp.ModelDatabase')),
            ],
        ),
        migrations.CreateModel(
            name='ModelURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.CharField(max_length=50)),
                ('url_encoded', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ModelView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_name', models.CharField(max_length=50)),
                ('type', models.CharField(blank=True, max_length=20)),
                ('view_code', models.TextField()),
                ('model_database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseApp.ModelDatabase')),
            ],
        ),
        migrations.AddField(
            model_name='modelurl',
            name='url_view',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseApp.ModelView'),
        ),
    ]
